"""Generate plain-text dispute letter."""
from datetime import datetime
from typing import List, Dict, Any


def generate_dispute_letter(batch: Any, discrepancies: List[Any], provider: str) -> str:
    now = datetime.utcnow().strftime("%d %B %Y")
    total_overcharge = sum(d.overcharge_amount for d in discrepancies)
    critical = [d for d in discrepancies if d.severity == "critical"]
    high = [d for d in discrepancies if d.severity == "high"]

    lines = [
        "=" * 70,
        "BILLING DISPUTE LETTER",
        "=" * 70,
        f"Date: {now}",
        f"To: {provider} Billing Department",
        f"Re: Invoice Audit Discrepancies — Batch #{batch.id}",
        f"Invoice File: {batch.invoice_file}",
        "",
        "Dear Sir/Madam,",
        "",
        "We have conducted a detailed audit of the shipping invoice(s) referenced above",
        f"against our executed rate contract. Our audit has identified {len(discrepancies)} discrepancies",
        f"resulting in a total overcharge of INR {total_overcharge:,.2f}.",
        "",
        "We hereby formally dispute the overcharged amounts and request a credit note",
        "or refund within 15 working days of receipt of this letter.",
        "",
        "-" * 70,
        "DISCREPANCY SUMMARY",
        "-" * 70,
        f"Total Discrepancies : {len(discrepancies)}",
        f"Critical            : {len(critical)}",
        f"High                : {len(high)}",
        f"Total Overcharge    : INR {total_overcharge:,.2f}",
        "",
        "-" * 70,
        "DETAILED DISCREPANCIES",
        "-" * 70,
    ]

    for i, d in enumerate(discrepancies, 1):
        lines += [
            f"\n[{i}] AWB: {d.awb_number}",
            f"    Type      : {d.check_type.replace('_', ' ').title()}",
            f"    Severity  : {d.severity.upper()}",
            f"    Issue     : {d.description}",
            f"    Overcharge: INR {d.overcharge_amount:,.2f}",
            f"    Confidence: {d.confidence_score * 100:.0f}%",
        ]
        if d.billed_value is not None:
            lines.append(f"    Billed    : INR {d.billed_value:,.2f}")
        if d.expected_value is not None:
            lines.append(f"    Expected  : INR {d.expected_value:,.2f}")

    lines += [
        "",
        "-" * 70,
        "REQUESTED ACTION",
        "-" * 70,
        f"Please issue a credit note for INR {total_overcharge:,.2f} at the earliest.",
        "If you require any additional documentation, please contact us.",
        "",
        "Yours faithfully,",
        "[Your Name / Company]",
        "[Contact Details]",
        "",
        "=" * 70,
        f"Generated by BillCheck on {now}",
        "=" * 70,
    ]

    return "\n".join(lines)
